//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrizzTime.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class business
    {
        public int UserID { get; set; }
        public string UserEmail { get; set; }
        public string UserPW { get; set; }
        public string UserStatus { get; set; }
        public int BusCode { get; set; }
        public string BusName { get; set; }
        public string BusDesc { get; set; }
        public string BusAddress { get; set; }
    }
}
