//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrizzTime.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public project()
        {
            this.employee_project = new HashSet<employee_project>();
        }
    
        public int ProjID { get; set; }
        public string ProjName { get; set; }
        public string ProjDesc { get; set; }
        public System.DateTime ProjStartDate { get; set; }
        public string ProjStatus { get; set; }
        public Nullable<System.DateTime> ProjEndDate { get; set; }
        public Nullable<int> ProjManagerID { get; set; }
    
        public virtual employee employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee_project> employee_project { get; set; }
    }
}
