//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrizzTime.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJECT
    {
        public int projId { get; set; }
        public string projName { get; set; }
        public string projDesc { get; set; }
        public decimal projPayRate { get; set; }
        public System.DateTime projStartDate { get; set; }
        public Nullable<System.DateTime> projEndDate { get; set; }
        public bool projIsComplete { get; set; }
    }
}
