
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GrizzTime.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ptorequest
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ptorequest()
    {

        this.ptorequestdays = new HashSet<ptorequestday>();

    }


    public int PTORequestID { get; set; }

    public string PTORequestStatus { get; set; }

    public decimal PTORequestHrTot { get; set; }

    public Nullable<System.DateTime> PTORequestSubmitDate { get; set; }

    public string PTORequestApproveDate { get; set; }

    public string PTORequestReason { get; set; }

    public int EmpID { get; set; }



    public virtual employee employee { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ptorequestday> ptorequestdays { get; set; }

}

}
