
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GrizzTime.Models
{

using System;
    using System.Collections.Generic;
    
public partial class timesheet
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public timesheet()
    {

        this.workentries = new HashSet<workentry>();

    }


    public int TimeSheetID { get; set; }

    public int PayrollCycleID { get; set; }

    public int EmpID { get; set; }

    public string TimeSheetStatus { get; set; }

    public decimal TimeSheetTotalHr { get; set; }

    public Nullable<System.DateTime> TimeSheetSubmitTime { get; set; }

    public Nullable<System.DateTime> TimeSheetApproveTime { get; set; }



    public virtual employee employee { get; set; }

    public virtual payrollcycle payrollcycle { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<workentry> workentries { get; set; }

}

}
