//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrizzTime.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Web;

    public partial class User
    {
        public int UserID { get; set; }
        [Display(Name = "First name")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "first name required")]
        public string firstName { get; set; }
        [Display(Name = "Last name")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "last name required")]
        public string lastName { get; set; }
        [Display(Name = "Email")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "email required")]
        public string email { get; set; }
        [Display(Name = "Password")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "password required")]
        public string password { get; set; }
        public string phone { get; set; }
        [Display(Name = "Phone")]
        public bool RememberMe { get; set; }
    }
}
